version: "3.7"
services:
  app:
    build:
      args:
        user: niagahoster
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    image: niagahoster
    container_name: niagahoster-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - niagahoster

  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: niagahoster_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: mydb
      MYSQL_USER: mydb
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - niagahoster

  phpmyadmin:
    container_name: niagahoster-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1

  nginx:
    image: nginx:alpine
    container_name: niagahoster-nginx
    restart: unless-stopped
    ports:
      - "8004:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - niagahoster

networks:
  niagahoster:
    driver: bridge